name: Publish create-astro-sitecore-jss to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        working-directory: ./astro-sitecore-jss/packages/create-astro-sitecore-jss
        run: npm install
      - name: Build package
        working-directory: ./astro-sitecore-jss/packages/create-astro-sitecore-jss
        run: npm run build
      - name: Publish package on NPM 📦
        working-directory: ./astro-sitecore-jss/packages/create-astro-sitecore-jss
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}